### ISSUE TITLE
can't connect vehicle

### ISSUE THREAD

**Issue by wil76** [CONSULitAS/Polestar_2_MQTT_Docker#11]
it has been working for a while, but cannot connect any more, upgrade doesn't help

Updating 084e335..6f130b1
Fast-forward
 .github/workflows/linter.yml |  2 +-
 Dockerfile                   |  6 +++---
 Polestar_2_MQTT.py           | 22 ++++++++++++----------
 README.md                    | 20 +++++++++++++++-----
 Synology-howto.md            | 37 +++++++++++++++++++++++++++++++++++++
 docker-compose_example.yml   | 28 +++++++++++++++++++++++++---
 6 files changed, 93 insertions(+), 22 deletions(-)
 create mode 100644 Synology-howto.md
(py_shng) smarthome@raspiP4book:/home/polestar $ docker compose up
[+] Running 1/1
 ✔ Container polestar2mqtt  Recreated                                                                                                            0.3s
Attaching to polestar2mqtt
polestar2mqtt  | /app/Polestar_2_MQTT.py:28: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
polestar2mqtt  |   client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
polestar2mqtt  | Polestar_2_MQTT.py startet
polestar2mqtt  | ==========================
polestar2mqtt  | Connected with result code 0get_token()
polestar2mqtt  |
polestar2mqtt  |  get_login_tokens()
polestar2mqtt  |   cookies    = PF=PMIP2fnAnyb0FcvlzE2BjA; Path=/; Expires=Wed, 20-Nov-2024 13:26:38 GMT; Max-Age=3600; Secure; HttpOnly; SameSite=Non             e
polestar2mqtt  |   cookie     = PF=PMIP2fnAnyb0FcvlzE2BjA
polestar2mqtt  |   path_token = FeuFW3ohdT
polestar2mqtt  |  perform_login()
polestar2mqtt  |   max_age    = 15780000
polestar2mqtt  |   uid        = 240e3815-06ac-4b13-bec7-25705f33d471
polestar2mqtt  |   code       = NONE
polestar2mqtt  |   GOT CODE!       = mhJceLg3FOmnw8kDOMYmM33CxSum2O84S1UI01zU
polestar2mqtt  |  get_api_token()
polestar2mqtt  |   access_token  = eyJhbGciOiJSUzI1NiIsImtpZCI6IkVhUlZmX3l...
polestar2mqtt  |   refresh_token = i8ha5WKNzwSMNjC9dudbtcYH8fTPyqCFnewsRgywbq
polestar2mqtt  |   expires_in    = 299
polestar2mqtt  |   expiry_time   = 2024-11-20 13:31:38 CET+0100
polestar2mqtt  | get_car_data()
polestar2mqtt  |   response.status_code = 404
polestar2mqtt  | <Response [404]>
polestar2mqtt  | Fehler: get_car_data() Datenabfrage fehlgeschlagen
polestar2mqtt  | Fehler in Zeile: 193
polestar2mqtt  | Fehlertyp und Nachricht: Exception get_car_data() Datenabfrage fehlgeschlagen
polestar2mqtt  | Traceback (most recent call last):
polestar2mqtt  |   File "/app/Polestar_2_MQTT.py", line 334, in <module>
polestar2mqtt  |     main()
polestar2mqtt  |     ~~~~^^
polestar2mqtt  |   File "/app/Polestar_2_MQTT.py", line 302, in main
polestar2mqtt  |     car_data = get_car_data(POLESTAR_VIN, access_token)
polestar2mqtt  |   File "/app/Polestar_2_MQTT.py", line 193, in get_car_data
polestar2mqtt  |     raise Exception("get_car_data() Datenabfrage fehlgeschlagen")
polestar2mqtt  | Exception: get_car_data() Datenabfrage fehlgeschlagen
polestar2mqtt  |
polestar2mqtt exited with code 0
(py_shng) smarthome@raspiP4book:/home/polestar $

**Comment by wil76** [comment]
have newly build
and it works again
thanks
