### ISSUE TITLE
API change: challenge+is+required

### ISSUE THREAD

**Issue by CONSULitAS** [CONSULitAS/Polestar_2_MQTT_Docker#13]
```
polestar2mqtt  | Polestar_2_MQTT.py startet
polestar2mqtt  | ==========================
polestar2mqtt  | get_token()
polestar2mqtt  |  get_login_tokens()
polestar2mqtt  | Connected with result code Success
polestar2mqtt  | Fehler: list index out of range
polestar2mqtt  | Fehler in Zeile: 65
polestar2mqtt  | Fehlertyp und Nachricht: IndexError list index out of range
polestar2mqtt  | Traceback (most recent call last):
polestar2mqtt  |   File "/app/Polestar_2_MQTT.py", line 336, in <module>
polestar2mqtt  |     main()
polestar2mqtt  |     ~~~~^^
polestar2mqtt  |   File "/app/Polestar_2_MQTT.py", line 301, in main
polestar2mqtt  |     access_token, expiry_time, refresh_token = get_token(POLESTAR_EMAIL, POLESTAR_PASSWORD)
polestar2mqtt  |                                                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polestar2mqtt  |   File "/app/Polestar_2_MQTT.py", line 146, in get_token
polestar2mqtt  |     path_token, cookie = get_login_tokens()
polestar2mqtt  |                          ~~~~~~~~~~~~~~~~^^
polestar2mqtt  |   File "/app/Polestar_2_MQTT.py", line 65, in get_login_tokens
polestar2mqtt  |     path_token = response.headers.get('Location').split("resumePath=")[1].split("&")[0]
polestar2mqtt  |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
polestar2mqtt  | IndexError: list index out of range
```

`'location': 'https://www.polestar.com/sign-in-callback?error_description=code_challenge+is+required.&error=invalid_request#.'`

**Comment by nanoq66** [comment]
ah that's the same issue I got. and the HACS integration, see: https://github.com/pypolestar/polestar_api/issues/261
